#ifndef FIRMWARE_DRIVERS_SYSCTRL_H
#define FIRMWARE_DRIVERS_SYSCTRL_H

#define SYSCTRL_ID_EXPECTED       0x4C544353U
#define SYSCTRL_BOOT_FLASH_LOADED 0x1U
#define SYSCTRL_BOOT_VECTOR_VALID 0x2U
#define SYSCTRL_BOOT_SECURE_DONE  0x4U
#define SYSCTRL_BOOT_SECURE_PASS  0x8U
#define SYSCTRL_CPU1_RELEASED     0x2U

void sysctrl_release_cpu1(void);
void test_sysctrl(void);

#endif /* FIRMWARE_DRIVERS_SYSCTRL_H */
