#ifndef KX6625_AWTK_CONFIG_H
#define KX6625_AWTK_CONFIG_H

#define USE_GUI_MAIN 1
#define AWTK_LITE 1
#define WITH_BITMAP_FONT 1
#define WITH_NULL_IM 1
#define WITH_LCD_RGB565 1
#define TK_HEAP_MEM_SIZE (24 * 1024)
#define TK_GLYPH_CACHE_NR 16
#define MAIN_LOOP_QUEUE_SIZE 8
#define WITHOUT_LAYOUT 1
#define WITHOUT_FSCRIPT 1
#define WITHOUT_XML_STYLE 1
#define WITHOUT_CLIPBOARD 1
#define WITHOUT_EXT_WIDGETS 1
#define WITHOUT_INPUT_METHOD 1
#define WITHOUT_WINDOW_ANIMATORS 1
#define WITHOUT_WIDGET_ANIMATORS 1
#define WITHOUT_DIALOG_HIGHLIGHTER 1
#define WITHOUT_ROUNDED_RECT 1

#endif /* KX6625_AWTK_CONFIG_H */