name: Build and Test

on:
  push:
    branches: [ main, "copilot/*" ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install ARM toolchain
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-arm-none-eabi
    
    - name: Build firmware
      run: make fw
    
    - name: Test protocol implementation
      run: make test
    
    - name: Verify firmware binary exists
      run: |
        ls -la build/firmware.bin
        file build/firmware.bin
    
    - name: Check firmware size
      run: |
        echo "Firmware size:"
        stat -c%s build/firmware.bin
        echo "bytes"
    
    # Note: Skip QEMU build in CI due to time constraints
    # Can be enabled for more thorough testing
    # - name: Build QEMU (optional)
    #   run: make qemu